import { NextRequest, NextResponse } from "next/server";
import { getUserId, getActiveTeam } from "@/lib/auth";
import { db } from "@/lib/db";
import { rosters, teams, users } from "@/lib/schema";
import { and, eq } from "drizzle-orm";
import { getValidAccessToken, SPOTIFY_API_BASE, DEFAULT_WALK_UP_SONGS, findCleanTrack } from "@/lib/spotify";
import type { Player, WalkOnSong } from "@/lib/types";

interface SyncResult {
  ok: boolean;
  reason?: string;
  playlistId?: string;
  playlistUrl?: string;
  trackCount?: number;
  /** present players whose missing songs got auto-assigned a default */
  defaulted?: number;
  /** present players we couldn't find any song for (default search came up empty) */
  skipped?: number;
}

/**
 * Create or update the active team's "{TeamName} Walk On Music" playlist
 * with each present player's walk-on song in batting order. Soft-fails so
 * the caller (typically the Generate Roster handler) never blocks on
 * Spotify being misconfigured, disconnected, or unreachable.
 */
export async function POST(request: NextRequest): Promise<NextResponse<SyncResult>> {
  const userId = getUserId(request);
  if (!userId) return NextResponse.json({ ok: false, reason: "unauthorized" }, { status: 401 });

  const team = await getActiveTeam(request);
  if (!team) return NextResponse.json({ ok: false, reason: "no_active_team" });

  const token = await getValidAccessToken(userId);
  if (!token) return NextResponse.json({ ok: false, reason: "spotify_not_connected" });

  const [user] = await db.select({ spotifyUserId: users.spotifyUserId }).from(users).where(eq(users.id, userId)).limit(1);
  const spotifyUserId = user?.spotifyUserId;
  if (!spotifyUserId) return NextResponse.json({ ok: false, reason: "no_spotify_profile" });

  // Build the ordered track URI list from present players, in rank (batting) order.
  const [roster] = await db
    .select({ players: rosters.players })
    .from(rosters)
    .where(and(eq(rosters.userId, userId), eq(rosters.teamId, team.id)))
    .limit(1);

  const players = (roster?.players as Player[] | undefined) ?? [];
  const present = [...players].filter(p => !p.absent).sort((a, b) => a.rank - b.rank);

  // Auto-fill defaults for any present player without a song. Avoid duplicates
  // both with already-picked songs and across the rotation. Pull from
  // DEFAULT_WALK_UP_SONGS in a fresh shuffle each sync so teams that never
  // pick songs still get a varied playlist over time.
  const usedSpotifyIds = new Set<string>();
  for (const p of present) if (p.walkOnSong?.spotifyId) usedSpotifyIds.add(p.walkOnSong.spotifyId);

  const defaultPool = [...DEFAULT_WALK_UP_SONGS].sort(() => Math.random() - 0.5);
  let defaultIdx = 0;
  let defaulted = 0;
  let skipped = 0;
  let rosterMutated = false;
  const updatedPlayers = [...players];

  for (const p of present) {
    if (p.walkOnSong?.uri) continue;
    // Try the rotation, skipping any whose resolved track is already used.
    let assigned: WalkOnSong | null = null;
    for (let attempt = 0; attempt < defaultPool.length && !assigned; attempt++) {
      const candidate = defaultPool[(defaultIdx + attempt) % defaultPool.length];
      const found = await findCleanTrack(token, candidate.title, candidate.artist);
      if (!found) continue;
      if (usedSpotifyIds.has(found.spotifyId)) continue;
      assigned = { ...found, isDefaultPick: true };
      defaultIdx = (defaultIdx + attempt + 1) % defaultPool.length;
    }
    if (!assigned) {
      skipped++;
      continue;
    }
    usedSpotifyIds.add(assigned.spotifyId);
    defaulted++;
    rosterMutated = true;
    // Mutate the player in the rosterPlayers copy so we persist back.
    const playerIdx = updatedPlayers.findIndex((x) => x.id === p.id);
    if (playerIdx >= 0) updatedPlayers[playerIdx] = { ...updatedPlayers[playerIdx], walkOnSong: assigned };
  }

  if (rosterMutated && roster) {
    await db
      .update(rosters)
      .set({ players: updatedPlayers })
      .where(and(eq(rosters.userId, userId), eq(rosters.teamId, team.id)));
  }

  // Now build trackUris in batting order from the (possibly updated) list.
  const trackUris: string[] = [];
  for (const p of present) {
    const updated = updatedPlayers.find((x) => x.id === p.id) ?? p;
    if (updated.walkOnSong?.uri) trackUris.push(updated.walkOnSong.uri);
  }

  const playlistName = `${team.name} Walk On Music`;
  const playlistDescription = `Walk-on songs in batting order. Auto-generated by Who's On First — last sync ${new Date().toISOString().slice(0, 10)}.`;

  // Try the cached playlist id first. If Spotify 404s (deleted by user) or
  // the name has drifted, create a fresh one.
  let playlistId = team.spotifyPlaylistId ?? null;

  if (playlistId) {
    const check = await fetch(`${SPOTIFY_API_BASE}/playlists/${playlistId}`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!check.ok) playlistId = null;
  }

  if (!playlistId) {
    const createRes = await fetch(`${SPOTIFY_API_BASE}/users/${spotifyUserId}/playlists`, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        name: playlistName,
        description: playlistDescription,
        public: true,
        collaborative: false,
      }),
    });
    if (!createRes.ok) {
      const body = await createRes.text().catch(() => "");
      console.error(`[spotify/sync] create playlist failed ${createRes.status}: ${body.slice(0, 300)}`);
      return NextResponse.json({ ok: false, reason: `create_failed_${createRes.status}` });
    }
    const created = (await createRes.json()) as { id: string };
    playlistId = created.id;
    await db.update(teams).set({ spotifyPlaylistId: playlistId }).where(eq(teams.id, team.id));
  } else {
    // Update name/description in case team was renamed since last sync.
    await fetch(`${SPOTIFY_API_BASE}/playlists/${playlistId}`, {
      method: "PUT",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({ name: playlistName, description: playlistDescription, public: true }),
    });
  }

  // Replace the playlist's items wholesale with the new ordered URIs. Spotify
  // accepts up to 100 URIs per replace call — way more than any roster ever
  // needs, so a single PUT is enough.
  const replaceRes = await fetch(`${SPOTIFY_API_BASE}/playlists/${playlistId}/tracks`, {
    method: "PUT",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ uris: trackUris }),
  });
  if (!replaceRes.ok) {
    const body = await replaceRes.text().catch(() => "");
    console.error(`[spotify/sync] replace tracks failed ${replaceRes.status}: ${body.slice(0, 300)}`);
    return NextResponse.json({ ok: false, reason: `replace_failed_${replaceRes.status}` });
  }

  return NextResponse.json({
    ok: true,
    playlistId,
    playlistUrl: `https://open.spotify.com/playlist/${playlistId}`,
    trackCount: trackUris.length,
    defaulted,
    skipped,
  });
}
